### ISSUE TITLE
Rename your application name.

### ISSUE THREAD

**Issue by Psyker** [Liinkiing/browsear#1]
I think that "Brows'ear" is not bad !

**Comment by Liinkiing** [comment]
I think that it is a great name!
Will be renaming the repository 
![tenor](https://user-images.githubusercontent.com/17753997/69982074-e653fa00-1533-11ea-9235-3b9367d0abd5.gif)

**Comment by Liinkiing** [comment]
Closed by c7d019f9c02805171aa2110e1c7c83030212c9b5
